training_params:
  device : cuda
  num_epochs : 150
  optimizer: schedulefree.AdamWScheduleFree
  optimizer_params:
    lr: 0.001
    weight_decay: 0.0001
  scheduler: null
  scheduler_params: {}
  criterion: dinozaur.training.losses.RelativeLpLoss
  criterion_params: {}

model_params:
  architecture: dinozaur.models.GINOd
  architecture_params: 
    input_size: 1
    output_size: 1
    n_positional_encoding_frequencies: 16
    width: 64
    modes: [24, 24, 24]
    include_gradient_features: True
    factorization: tucker
    factorization_rank: 0.4
    domain_padding: 0.125
    padding_mode: symmetric

data_params:
  data_folder: data/shapenetcar
  batch_size : 1
  features: ["surface.min_max_normalized_sdf"]
  extra_inputs:
    grid_points: surface.min_max_normalized_sdf_query_points
    out_points: surface.min_max_normalized_vertices
    u_nu_neighbor_index: surface.min_max_normalized_neighbors_index_decoder
    u_nu_neighbor_row_splits: surface.min_max_normalized_neighbors_row_splits_decoder
  target: "surface.pressure"
  x_normalizer_class: dinozaur.training.scalers.IdentityScaler
  y_normalizer_class: dinozaur.training.scalers.GaussianScaler